config/routes.rb
Spree::Core::Engine.add_routes do
  devise_for :spree_user,
             class_name: Spree::User,
             skip: [:unlocks, :sessions, :registrations, :passwords],
             controllers: { omniauth_callbacks: 'spree/omniauth_callbacks' },
             path: Spree::SocialConfig[:path_prefix]
  resources :user_authentications

  get 'account' => 'users#show', as: 'user_root'

  namespace :admin do
    resources :authentication_methods
  end
end

app/models/spree/authentication_method.rb
class Spree::AuthenticationMethod < ActiveRecord::Base
  validates :provider, :api_key, :api_secret, presence: true

  def self.active_authentication_methods?
    where(environment: ::Rails.env, active: true).exists?
  end

  scope :available_for, lambda { |user|
    sc = where(environment: ::Rails.env)
    sc = sc.where(['provider NOT IN (?)', user.user_authentications.map(&:provider)]) if user && !user.user_authentications.empty?
    sc
  }
end

app/models/spree/social_configuration.rb
module Spree
  class SocialConfiguration < Preferences::Configuration
    preference :path_prefix, :string, default: 'users'
  end
end

app/models/spree/user_authentication.rb
class Spree::UserAuthentication < ActiveRecord::Base
  belongs_to :user
end

app/models/spree/user_decorator.rb
Spree.user_class.class_eval do
  has_many :user_authentications, dependent: :destroy

  devise :omniauthable

  def apply_omniauth(omniauth)
    if %w(facebook google_oauth2).include? omniauth['provider']
      self.email = omniauth['info']['email'] if email.blank?
    end
    user_authentications.build(provider: omniauth['provider'], uid: omniauth['uid'])
  end

  def password_required?
    (user_authentications.empty? || !password.blank?) && super
  end
end

app/controllers/spree/admin/authentication_methods_controller.rb
module Spree
  module Admin
    class AuthenticationMethodsController < ResourceController
      create.after :update_oauth_method
      update.after :update_oauth_method

      private

      def update_oauth_method
        auth_method = params[:authentication_method]
        return unless auth_method[:active] == 'true' && auth_method[:environment] == ::Rails.env
        Devise.setup do |config|
          config.omniauth auth_method[:provider], auth_method[:api_key], auth_method[:api_secret]
        end
      end
    end
  end
end

app/controllers/spree/omniauth_callbacks_controller.rb
class Spree::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  include Spree::Core::ControllerHelpers::Common
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::SSL
  include Spree::Core::ControllerHelpers::Store

  def self.provides_callback_for(*providers)
    providers.each do |provider|
      class_eval <<-FUNCTION_DEFS, __FILE__, __LINE__ + 1
        ssl_allowed :#{provider}
        def #{provider}
          if request.env['omniauth.error'].present?
            flash[:error] = I18n.t('devise.omniauth_callbacks.failure', kind: auth_hash['provider'], reason: Spree.t(:user_was_not_valid))
            redirect_back_or_default(root_url)
            return
          end

          authentication = Spree::UserAuthentication.find_by_provider_and_uid(auth_hash['provider'], auth_hash['uid'])

          if authentication.present? and authentication.try(:user).present?
            flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: auth_hash['provider'])
            sign_in_and_redirect :spree_user, authentication.user
          elsif spree_current_user
            spree_current_user.apply_omniauth(auth_hash)
            spree_current_user.save!
            flash[:notice] = I18n.t('devise.sessions.signed_in')
            redirect_back_or_default(account_url)
          else
            user = Spree::User.find_by_email(auth_hash['info']['email']) || Spree::User.new
            user.apply_omniauth(auth_hash)
            if user.save
              flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: auth_hash['provider'])
              sign_in_and_redirect :spree_user, user
            else
              session[:omniauth] = auth_hash.except('extra')
              flash[:notice] = Spree.t(:one_more_step, kind: auth_hash['provider'].capitalize)
              redirect_to new_spree_user_registration_url
              return
            end
          end

          if current_order
            user = spree_current_user || authentication.user
            current_order.associate_user!(user)
            session[:guest_token] = nil
          end
        end
      FUNCTION_DEFS
    end
  end

  SpreeSocial::OAUTH_PROVIDERS.each do |provider|
    provides_callback_for provider[1].to_sym
  end

  def failure
    set_flash_message :alert, :failure, kind: failed_strategy.name.to_s.humanize, reason: failure_message
    redirect_to spree.login_path
  end

  def passthru
    render file: "#{Rails.root}/public/404", formats: [:html], status: 404, layout: false
  end

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/spree/user_authentications_controller.rb
class Spree::UserAuthenticationsController < Spree::StoreController
  def index
    @authentications = spree_current_user.user_authentications if spree_current_user
  end

  def destroy
    @authentication = spree_current_user.user_authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = Spree.t(:destroy, scope: :authentications)
    redirect_to spree.account_path
  end
end

app/controllers/spree/user_registrations_controller_decorator.rb
Spree::UserRegistrationsController.class_eval do
  after_action :clear_omniauth, only: :create

  private

  def build_resource(*args)
    super
    @spree_user.apply_omniauth(session[:omniauth]) if session[:omniauth]
    @spree_user
  end

  def clear_omniauth
    session[:omniauth] = nil unless @spree_user.new_record?
  end
end

app/helpers/spree/omniauth_callbacks_helper.rb
module Spree
  module OmniauthCallbacksHelper
    include Spree::BaseHelper
  end
end

app/views/spree/admin/authentication_methods/_form.html.erb
<%= form_for [:admin, resource] do |f| %>

  <div data-hook="admin_social_methods_form_fields">
    <div class="row">
      <div class="col-md-6">
        <div data-hook="environment" class="form-group">
          <%= label_tag nil, Spree.t(:environment) %>
          <%= collection_select :authentication_method, :environment, Rails.configuration.database_configuration.keys, :to_s, :titleize, {}, class: 'select2' %>
        </div>
      </div>
      <div class="col-md-6">
        <div data-hook="environment" class="form-group">
          <%= f.label :provider, Spree.t(:social_provider) %>
          <%= f.select :provider, SpreeSocial::OAUTH_PROVIDERS, {}, { include_blank: false, class: 'select2' } %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <div data-hook="environment" class="form-group">
          <%= f.label :api_key, Spree.t(:social_api_key) %>
          <%= f.text_field :api_key, class: 'form-control' %>
        </div>
      </div>
      <div class="col-md-6">
        <div data-hook="environment" class="form-group">
          <%= f.label :api_secret, Spree.t(:social_api_secret) %>
          <%= f.text_field :api_secret, class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <div data-hook="environment" class="form-group">
          <%= f.label :active, class: 'radio-inline' do %>
            <%= f.radio_button :active, :true %>
            <%= Spree.t(:active) %>
          <% end %>
          <%= f.label :active, class: 'radio-inline' do %>
            <%= f.radio_button :active, :false %>
            <%= Spree.t(:inactive) %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <%= render "spree/admin/shared/#{resource.new_record? ? 'new' : 'edit'}_resource_links" %>
<% end %>

app/views/spree/admin/authentication_methods/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:edit_social_method) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:back_to_authentication_methods_list), admin_authentication_methods_path, icon: 'arrow-left', class: 'btn-primary' %>
<% end %>

<%= render 'form', resource: @authentication_method %>

app/views/spree/admin/authentication_methods/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:social_authentication_methods) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_social_method), new_object_url, icon: 'add', class: 'btn-success', id: 'admin_new_slide_link' %>
<% end %>

<% if @authentication_methods.any? %>
  <table class="table" id="listing_trackers">
    <thead data-hook="admin_social_methods_index_headers">
      <th><%= Spree.t(:social_provider) %></th>
      <th><%= Spree.t(:social_api_key) %></th>
      <th><%= Spree.t(:social_api_secret) %></th>
      <th><%= Spree.t(:environment) %></th>
      <th><%= Spree.t(:active) %></th>
      <th data-hook="admin_social_methods_index_header_actions" class="actions"></th>
    </thead>
    <tbody>
      <% @authentication_methods.each do |method| %>
        <tr id="<%= dom_id method %>" data-hook="admin_trackers_index_rows" class="<%= cycle('odd', 'even') %>">
          <td><%= method.provider %></td>
          <td><%= truncate method.api_key, length: 20 %></td>
          <td><%= truncate method.api_secret, length: 20 %></td>
          <td><%= method.environment.to_s.titleize %></td>
          <td><%= method.active ? Spree.t(:yes) : Spree.t(:no) %></td>
          <td class="actions">
            <%= link_to_edit method, no_text: true %>
            <%= link_to_delete method, no_text: true %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-warning no-objects-found">
    <%= Spree.t(:no_authentication_methods_found) %>,
    <%= Spree.t(:add_one) %>!
  </div>
<% end %>

app/views/spree/admin/authentication_methods/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_social_method) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:back_to_authentication_methods_list), admin_authentication_methods_path, icon: 'arrow-left', class: 'btn-primary' %>
<% end %>

<%= render 'form', resource: @authentication_method %>

app/views/spree/admin/shared/_configurations_menu.html.erb
<tr>
  <td><%= link_to Spree.t(:social_authentication_methods), spree.admin_authentication_methods_path %></td>
  <td><%= Spree.t(:social_authentication_methods_description) %></td>
</tr>

app/views/spree/shared/_social.html.erb
<div id="social-signin-links">
  <% if (!spree_current_user || !spree_current_user.user_authentications) && Spree::AuthenticationMethod.active_authentication_methods? %>
    <h4><%= Spree.t(:sign_in_through_one_of_these_services) %></h4>
  <% end %>

  <% Spree::AuthenticationMethod.available_for(@spree_user).each do |method| %>
    <%= link_to(content_tag(:i, '', class: "icon-spree-#{method.provider.to_url}-circled"),
          spree.spree_user_omniauth_authorize_url(provider: method.provider),
          id: method.provider.to_url,
          title: Spree.t(:sign_in_with, provider: method.provider)) if method.active %>
  <% end %>
</div>

app/views/spree/shared/_user_form.html.erb
<div class="form-group">
  <%= f.label :email, Spree.t(:email) %>
  <%= f.email_field :email, class: 'form-control' %>
</div>

<% if spree_current_user.nil? || spree_current_user.password_required? %>
  <div id="password-credentials">
    <div class="form-group">
      <%= f.label :password, Spree.t(:password) %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, Spree.t(:confirm_password) %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
  </div>
<% end %>

<div data-hook="signup_below_password_fields"></div>

app/views/spree/users/_new-customer.html.erb
<% if session[:omniauth] %>
  <h6><%= Spree.t(:please_confirm_your_email) %></h6>
<% else %>
  <h6><%= Spree.t(:new_customer) %></h6>
<% end %>

app/views/spree/users/_social.html.erb
<% if Spree::AuthenticationMethod.active_authentication_methods? %>
  <% @body_id = 'login' %>
  <div id="existing-customer">
    <% if spree_current_user.user_authentications %>
      <% unless spree_current_user.user_authentications.empty? %>
        <h4><%= Spree.t(:you_have_signed_in_with_these_services) %></h4>
        <div class="authentications">
          <% for user_authentication in spree_current_user.user_authentications %>
            <div class="authentication row">
              <div class="provider col-md-2">
                <%= content_tag(:i, '', class: "icon-spree-#{user_authentication.provider.to_url}-circled") %>
                <%= user_authentication.provider %>
              </div>
              <div class="uid col-md-3">
                <%= user_authentication.uid %>
              </div>
              <div class="col-md-2">
                <%= link_to user_authentication, data: { confirm: "#{Spree.t(:remove_authentication_option_confirmation)}" }, method: :delete, class: 'btn btn-default' do %>
                  <%= content_tag(:i, '', class: 'icon-delete') %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
    <%= content_tag(:p, content_tag(:strong, Spree.t(:add_another_service))) if Spree::AuthenticationMethod.available_for(spree_current_user).exists? %>
    <%= render 'spree/shared/social' %>
  </div>
  <div class="clear"></div>
<% end %>